version: '3.6'
services:

  learnappdrupal:
    hostname: ${DRUPAL_HOST}
    container_name: learnappdrupal
    restart: always
    image: learn/app/d${DRUPAL_VERSION}:${DRUPAL_TAG}
    environment:
      # ENV
      ENV_ID: ${ENV_ID}
      # PG
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_HOST: ${POSTGRES_HOST}
      POSTGRES_PORT: ${POSTGRES_PORT}
    build:
      dockerfile: ./config/${ENV_ID}/Dockerfile
      context: ./
      args:
        DRUPAL_HOST: ${DRUPAL_HOST}
        DRUPAL_VERSION: ${DRUPAL_VERSION}
    ports:
      - ${DRUPAL_PORT}:80
    volumes:
      - ./var/html/web/modules:/var/www/html/modules
      - ./var/html/web/profiles:/var/www/html/profiles
      - ./var/html/web/themes:/var/www/html/themes
      - ./var/html/web/libraries:/var/www/html/libraries
      - ./var/html/web/sites:/var/www/html/sites
      - ./var/html/config:/opt/drupal/config
      - ./var/html/translations:/opt/drupal/translations
      - ./var/html/features:/opt/drupal/features
      - ./var/html/composer.json:/opt/drupal/composer.json
      - ./var/html/behat.yml:/opt/drupal/behat.yml
      - ./config/${ENV_ID}/apache2/000-default.conf:/etc/apache2/sites-available/000-default.conf
      - ./config/${ENV_ID}/env/work/.bashrc:/root/.bashrc
    networks:
      - learnmigrationnet
    depends_on:
      - learnpg

  learnpgsql:
    container_name: learnpgsql
    image: postgres
    restart : always
    ports:
      - "${POSTGRES_CONTAINER_PORT}:5432"
    environment:
      ENV_ID: $${ENV_ID}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_HOST: ${POSTGRES_HOST}
      POSTGRES_PORT: ${POSTGRES_PORT}
    volumes:
      - ./postgresql/gln_pg_initdb:/docker-entrypoint-initdb.d
      - postgresql:/var/lib/postgresql/data
    networks:
      - learnmigrationnet

  learnpgsqladmin:
    container_name: learnpgsqladmin
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    ports:
      - "${PG_ADMIN_PORT}:80"
    networks:
      - learnmigrationnet
    depends_on:
      - learnpgsql

  # Postgres to store data
  learnmaria:
    container_name: learnmaria
    image: mariadb
    restart: always
    command: ['--character-set-server=utf8', '--collation-server=utf8_unicode_ci']
    volumes:
      - d8-maria-migrate:/var/lib/mysql
      #- '/Users/mm/Documents/Workspace/Docker/maison_dev/d8-shared:/tmp/plus'
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: d8magazin9
    ports:
     - ${MARIA_PORT}:3306
    networks:
      - learnmigrationnet

  # Adminer to manipulate db
  learndmnr:
    image: adminer
    container_name: learndmnr
    restart: always
    ports:
      - ${ADMINER_PORT}:8080
    networks:
      - learnmigrationnet
    depends_on:
      - learnmaria

volumes:
  modules:
    driver: local
  profiles:
    driver: local
  themes:
    driver: local
  libraries:
    driver: local
  sites:
    driver: local
  config:
    driver: local
  postgresql:
    driver: local
  gln_pg_initdb:
    driver: local
   # DB
  d8-maria-migrate:
    driver: local

networks:
  learnmigrationnet:
    driver: bridge
